<?php

use Drupal\Core\Utility\UpdateException;

/**
 * Implements hook_install().
 */
function premium_articles_install() {
  $config_factory = \Drupal::configFactory();

  $config = $config_factory->getEditable('views.view.taxonomy_term');
  $config->set('status', false);
  $config->save();

  $config = $config_factory->getEditable('core.entity_view_display.node.page.full');
  $third_party_settings = $config->get('third_party_settings');
  if (!empty($third_party_settings['layout_builder_restrictions']['entity_view_mode_restriction']['whitelisted_blocks']['Custom block types'])) {
    $third_party_settings['layout_builder_restrictions']['entity_view_mode_restriction']['whitelisted_blocks']['Custom block types'][] = 'articles';
    $third_party_settings['layout_builder_restrictions']['entity_view_mode_restriction']['whitelisted_blocks']['Custom block types'][] = 'article_form';
  }
  if (!empty($third_party_settings['layout_builder_restrictions']['entity_view_mode_restriction']['whitelisted_blocks']['Inline blocks'])) {
    $third_party_settings['layout_builder_restrictions']['entity_view_mode_restriction']['whitelisted_blocks']['Inline blocks'][] = 'inline_block:articles';
    $third_party_settings['layout_builder_restrictions']['entity_view_mode_restriction']['whitelisted_blocks']['Inline blocks'][] = 'inline_block:article_form';
  }
  $config->set('third_party_settings', $third_party_settings);
  $config->save();

}

/**
 * Implements hook_uninstall().
 */
function premium_articles_uninstall($is_syncing) {
  // Delete all articles
  $query = \Drupal::entityQuery('node');
  $query->condition('type', 'article');
  $nids = $query->execute();

  $storage_handler = \Drupal::entityTypeManager()->getStorage('node');
  $entities = $storage_handler->loadMultiple($nids);
  $storage_handler->delete($entities);

  $nodeType = \Drupal::entityTypeManager()->getStorage('node_type')->load('article');
  $nodeType->delete();

  // Delete all article types
  $query = \Drupal::entityQuery('taxonomy_term');
  $query->condition('vid', 'article_types');
  $tids = $query->execute();

  $storage_handler = \Drupal::entityTypeManager()->getStorage('taxonomy_term');
  $entities = $storage_handler->loadMultiple($tids);
  $storage_handler->delete($entities);

  // query all entities you want for example taxonomy term from tags vocabulary
  $query = \Drupal::entityQuery('taxonomy_term');
  $query->condition('vid', 'article_categories');
  $tids = $query->execute();

  $storage_handler = \Drupal::entityTypeManager()->getStorage('taxonomy_term');
  $entities = $storage_handler->loadMultiple($tids);
  $storage_handler->delete($entities);
}

/**
 * Prepare Entity Overview migration
 */
function premium_articles_update_9001(&$sandbox) {
  /** @var \Drupal\Core\Extension\ModuleInstaller $installer */
  $installer = \Drupal::service('module_installer');
  $module_data = \Drupal::service('extension.list.module')->reset()->getList();
  if (empty($module_data['entity_overview'])) {
    throw new UpdateException('You need to add Entity Overview to the project "composer require novicell/entity_overview"');
  }
  $installer->install(['entity_overview']);
}
