<?php

/**
 * @file
 * Contains merc_content_hierarchy_breadcrumb.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function premium_articles_breadcrumb_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the premium_articles_breadcrumb module.
    case 'help.page.premium_articles_breadcrumb':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Creates breadcrumbs based on article types') . '</p>';
      return $output;

    default:
  }
}
